# make_construction_isos.py
#
# Not-to-scale construction isometrics of the pig launcher's three spools,
# generated by Quetzal's iso generator (Quetzal with the iso/ and pcf/
# packages), one ANSI B page per spool, ft-in dimensions, NPS sizes:
#
#   PL-001  major barrel spool
#   PL-002  4" kicker line
#   PL-003  1" equalization line
#
# The spools are the App::Part containers made by
# examples/pig_trap_design/make_launcher_drawings.py. This macro never touches
# that model: it copies Header_with_pig_launcher.FCStd to
# launcher_construction_isos.FCStd beside this file, and works on the copy.
# The scaled drawings from make_launcher_drawings.py come along in the copy
# and are left as they are: the two kinds of drawing sit side by side.
#
# What it demonstrates -- see skills/techdraw-drawing/references/construction-iso.md:
#   * one sheet per spool: each top-level container is passed on its own,
#     and labelled for a person first, because the label becomes the title (17.1);
#   * units, size names, sheet and rotation set from the request, not from
#     the machine's Quetzal preference (17.2);
#   * console warnings captured, since they are the only report of skipped
#     parts and crowding (17.2);
#   * re-running updates the existing pages in place (update(), never delete
#     and recreate), so hand edits to the BOM and notes survive; restoring
#     the title block update() blanks; treating a None return as a
#     failure (17.3);
#   * the section 18 checks: every component drawn, BOM against the model,
#     every BOM item ballooned, every dimension on a model work point with
#     the right value and text.
#
# RUN IN THE FreeCAD GUI (Macro -> Execute). Units are mm internally.

import os
import shutil
import sys
from collections import Counter

import FreeCAD

try:
    import FreeCADGui
    _HAS_GUI = True
except Exception:
    _HAS_GUI = False


# ---------------------------------------------------------------------------
# Bootstrap: repo root and quetzal_env (puts Quetzal on sys.path)
# ---------------------------------------------------------------------------

def _repo_root():
    """Walk up from this file to the directory that holds quetzal_env.py."""
    try:
        here = os.path.dirname(os.path.abspath(__file__))
    except NameError:
        here = os.getcwd()  # __file__ undefined when exec()'d from the console
    while True:
        if os.path.isfile(os.path.join(here, "quetzal_env.py")):
            return here
        parent = os.path.dirname(here)
        if parent == here:
            raise RuntimeError(
                "Cannot find quetzal_env.py at or above %s -- run this macro "
                "from its place in the AI_Piping_Design repo." % here)
        here = parent


_ROOT = _repo_root()
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

import quetzal_env as qenv  # noqa: E402,F401

try:
    import pCmd  # noqa: E402
    from iso import iso_build, iso_format, iso_page, iso_sheet  # noqa: E402
    from pcf import pcf_export  # noqa: E402
except ImportError as e:
    raise RuntimeError("This Quetzal has no isometric generator (iso/ and pcf/ "
                       "packages): update Quetzal. (%s)" % e)

HERE = os.path.join(_ROOT, "examples", "construction_iso")
SOURCE = os.path.join(_ROOT, "examples", "pig_trap_design", "Header_with_pig_launcher.FCStd")
MODEL = os.path.join(HERE, "launcher_construction_isos.FCStd")


# ---------------------------------------------------------------------------
# What to draw
# ---------------------------------------------------------------------------

# Container label key -> label on the sheet. make_launcher_drawings.py
# tags its containers "LaunchDwg ..."; a fabricator should not read that.
# Each label must be unused in the document: FreeCAD makes labels unique, so
# reusing a scaled page's label ("PL-001 MAJOR BARREL SPOOL") would give the
# container, and so the iso title, "PL-001 MAJOR BARREL SPOOL001".
SPOOLS = (
    ("PL-001", "PL-001 BARREL SPOOL 8 IN"),
    ("PL-002", "PL-002 KICKER SPOOL 4 IN"),
    ("PL-003", "PL-003 EQUALIZATION SPOOL 1 IN"),
)

OPTIONS = dict(units="ftin", size_system="NPS", sheet=iso_sheet.ANSI_B,
               rotation=None,      # automatic: fewest clashes, then largest
               compression=None)   # fit pipe lengths to the sheet

TITLE = {"DrawnBy": "AI", "revision_index": "A",
         "CompanyName": "AI_Piping_Design example"}
TITLE_KEEP = ("CompanyName", "CompanyAddress", "DrawnBy", "CheckedBy",
              "Approved1", "Approved2", "revision_index", "Code", "Weight")


# ---------------------------------------------------------------------------
# Document
# ---------------------------------------------------------------------------

def open_copy():
    """The copy beside this file: already open, else copied and opened.
    The source model is never opened by this macro."""
    for d in FreeCAD.listDocuments().values():
        if os.path.normcase(os.path.abspath(d.FileName or "")) == os.path.normcase(MODEL):
            return d
    if not os.path.isfile(MODEL):
        if not os.path.isfile(SOURCE):
            raise RuntimeError("%s not found -- run make_pig_launcher.py and "
                               "make_launcher_drawings.py first" % SOURCE)
        shutil.copyfile(SOURCE, MODEL)
    return FreeCAD.openDocument(MODEL)


def spool_containers(doc):
    """[(container, sheet label)] in SPOOLS order; each must be top-level,
    or the page is named after the container around it (17.1)."""
    parts = [o for o in doc.Objects if o.TypeId == "App::Part"]
    out = []
    for key, label in SPOOLS:
        match = [p for p in parts if key in p.Label]
        if len(match) != 1:
            raise RuntimeError("expected one container for %s, found %s"
                               % (key, [p.Label for p in match]))
        part = match[0]
        if part.getParentGeoFeatureGroup() or part.getParentGroup():
            raise RuntimeError("%s is nested: its iso would be named after its parent"
                               % part.Label)
        out.append((part, label))
    return out


def existing_view(doc, part):
    """The iso view an earlier run made of this container, or None.
    Re-runs update it rather than deleting it: deletion throws away the
    user's BOM and notes edits, and deleting a page whose window is open
    leaves an orphaned window (it once ended in an access violation)."""
    # iso_views(doc.Objects) lists each view twice: once itself, once via its page
    unique = {v.Name: v for v in iso_page.iso_views(doc.Objects)}.values()
    views = [v for v in unique if list(v.IsoSource) == [part]]
    if len(views) > 1:
        raise RuntimeError("%d iso pages draw %s; expected at most one" % (len(views), part.Label))
    return views[0] if views else None


# ---------------------------------------------------------------------------
# Generate and regenerate
# ---------------------------------------------------------------------------

class Warnings:
    """Collect the generator's console warnings for the report."""

    def __enter__(self):
        self.items = []
        self._saved = iso_page._warn, pcf_export._log_warning
        iso_page._warn = lambda m: self.items.append(m)
        pcf_export._log_warning = lambda m: self.items.append(m)
        return self.items

    def __exit__(self, *exc):
        iso_page._warn, pcf_export._log_warning = self._saved
        return False


def set_title(view, fields):
    t = view.findParentPage().Template
    t.EditableTexts = dict(t.EditableTexts, **fields)  # a new dict (skill 4)


def regenerate(view):
    """update() keeping the title block, which it blanks (17.3).
    Returns the IsoSheet; raises when the page could not be redrawn."""
    t = view.findParentPage().Template
    saved = {k: v for k, v in t.EditableTexts.items() if k in TITLE_KEEP and v}
    sheet = iso_page.update(view)
    set_title(view, saved)
    if sheet is None:
        raise RuntimeError("%s: pipeline no longer found, page not updated" % view.IsoPipeline)
    return sheet


def build_all(doc):
    FreeCAD.setActiveDocument(doc.Name)
    if _HAS_GUI:
        FreeCADGui.setActiveDocument(doc.Name)
    opt = iso_build.Options(**OPTIONS)
    out = []
    for part, label in spool_containers(doc):
        part.Label = label  # the label becomes the pipeline reference and title
        if part.Label != label:
            raise RuntimeError("label %r is taken: FreeCAD made it %r" % (label, part.Label))
        view = existing_view(doc, part)
        warned = []
        if view is None:
            with Warnings() as warned:
                doc.openTransaction("Create isometric " + label)
                try:
                    pages = iso_page.pages_from_objects(doc, [part], opt)
                finally:
                    doc.commitTransaction()
            if len(pages) != 1:
                raise RuntimeError("%s gave %d pages, expected 1" % (label, len(pages)))
            view = iso_page.iso_views(pages)[0]
            set_title(view, TITLE)
        else:
            # A re-run: bring the stored inputs in line with OPTIONS and the
            # label, then regenerate in place.
            view.IsoPipeline = label  # update() finds its data by this name
            view.IsoUnits, view.IsoSizeSystem = opt.units, opt.size_system
            view.IsoSheetFormat = opt.sheet.name
            view.IsoRotation = -1 if opt.rotation is None else opt.rotation
            view.IsoCompression = opt.compression or 0.0
        with Warnings() as warned_again:
            sheet = regenerate(view)  # the IsoSheet for the checks, title kept
        out.append(dict(part=part, page=view.findParentPage(), view=view, sheet=sheet,
                        warnings=list(dict.fromkeys(warned + warned_again))))
    return out


def show(page):
    """One window, on one page (skill 11.6): none if that page already has
    one, since a second window onto a page renders blank."""
    if not _HAS_GUI:
        return
    gdoc = FreeCADGui.getDocument(page.Document.Name)
    for mdi_view in gdoc.mdiViewsOfType("TechDrawGui::MDIViewPage"):
        shown = mdi_view.getPage()
        if shown is not None and shown.Name == page.Name:
            return
    page.ViewObject.doubleClicked()
    FreeCADGui.updateGui()


# ---------------------------------------------------------------------------
# Verification (skill section 18)
# ---------------------------------------------------------------------------

def work_points(objs):
    """Ports, elbow/tee centres, and olet centres on the header centreline."""
    wps = []
    for o in objs:
        if not hasattr(o, "PType"):
            continue
        gp = o.getGlobalPlacement()
        to_world = gp.multiply(o.Placement.inverse())
        wps += [to_world.multVec(p) for p in (pCmd.portsPos(o) or [])]
        if o.PType in ("Elbow", "Tee", "SocketEll", "SocketTee"):
            wps.append(gp.Base)
        if o.PType == "Outlet":  # the olet's work point is on the run's centreline
            wps.append(gp.multVec(FreeCAD.Vector(0, 0, -qenv.val(getattr(o, "CarrierOD", 0)) / 2)))
    return wps


def report(doc, out):
    lines = ["", "=== Construction isometrics on %s ===" % doc.Label]
    bad = 0
    for r in out:
        view, sheet, part = r["view"], r["sheet"], r["part"]
        g = sheet.layout.graph
        et = view.findParentPage().Template.EditableTexts
        lines.append("  %s   page '%s'  rotation %d  %s  %s" % (
            view.IsoPipeline, r["page"].Label, sheet.layout.rotation, view.IsoUnits,
            view.IsoSheetFormat))

        # "shrunk" is crowding, to report at handover; anything else is a defect
        info = [w for w in r["warnings"] if "shrunk" in w]
        faults = [w for w in r["warnings"] if w not in info]
        lines.append("    %s warnings: %s%s" % ("OK " if not faults else "BAD", faults or "none",
                                                 "  (crowding: %s)" % info if info else ""))
        bad += len(faults)
        bad += len(g.skipped)
        lines.append("    not drawn: %s" % (g.skipped or "none"))

        # BOM against the model
        model = Counter(o.PType for o in part.Group if hasattr(o, "PType"))
        drawn = sum(len(it.comps) for it in sheet.bom)
        pipe_model = sum(qenv.val(o.Height) for o in part.Group if getattr(o, "PType", "") == "Pipe")
        pipe_bom = sum(it.length for it in sheet.bom if it.category == "PIPE")
        ok = drawn == sum(model.values()) and abs(pipe_model - pipe_bom) < 0.5
        bad += not ok
        lines.append("    %s BOM %d items covering %d components (model %d: %s); "
                     "pipe %.1f mm (model %.1f)" % (
                         "OK " if ok else "BAD", len(sheet.bom), drawn, sum(model.values()),
                         dict(model), pipe_bom, pipe_model))

        # every BOM number ballooned
        numbers = {it.number for it in sheet.bom}
        ballooned = {n for n, _c, _a in sheet.balloons}
        ok = numbers == ballooned
        bad += not ok
        lines.append("    %s balloons for %d of %d BOM items%s" % (
            "OK " if ok else "BAD", len(numbers & ballooned), len(numbers),
            "" if ok else ", missing %s" % sorted(numbers - ballooned)))

        # every dimension on a model work point, value along the run, text
        wps = work_points(part.Group)

        def near(p):
            return min((FreeCAD.Vector(*p) - w).Length for w in wps)

        for d in sheet.dimensions:
            a = FreeCAD.Vector(*g.nodes[d.a].pos)
            b = FreeCAD.Vector(*g.nodes[d.b].pos)
            dirs = [FreeCAD.Vector(*e.direction) for e in g.edges if d.a in (e.a, e.b)]
            along = max(abs((b - a).dot(u)) for u in dirs) if dirs else (b - a).Length
            ok = (abs(along - d.value) < 0.5 and near(a) < 1.0 and near(b) < 1.0
                  and d.text == iso_format.length_text(d.value, view.IsoUnits))
            bad += not ok
            lines.append("    %s dim %-12s %8.1f mm  model %8.1f mm  anchors off %.2f / %.2f mm"
                         % ("OK " if ok else "BAD", d.text, d.value, along, near(a), near(b)))

        # title block kept through update()
        missing = [k for k in TITLE if et.get(k) != TITLE[k]]
        bad += len(missing)
        lines.append("    %s title block: %s" % ("OK " if not missing else "BAD",
                                                  "kept" if not missing else "lost %s" % missing))
    lines.append("  Pages are not to scale; dimensions are true lengths in ft-in to 1/16 in.")
    lines.append("  %s" % ("ALL CHECKS PASSED" if not bad else "%d CHECK(S) FAILED" % bad))
    FreeCAD.Console.PrintMessage("\n".join(lines) + "\n")
    if bad:
        raise RuntimeError("%d isometric check(s) failed -- see the report" % bad)


def main():
    doc = open_copy()
    out = build_all(doc)
    show(out[0]["page"])
    report(doc, out)
    doc.save()
    FreeCAD.Console.PrintMessage("  Saved: %s\n" % doc.FileName)
    return doc


if __name__ == "__main__":
    main()
